### PR TITLE
Pin docker version to 1.8.2 during setup and fix dhcp options that wa…

### PR DESCRIPTION
**Pull request by cooktheryan**
Results of work with @abutcher just completed install and dhcp options fix the SDN error

### CODE REVIEW

**Comment by abutcher** [comment]
:+1: the DHCP options are something demo-ansible should manage. Docker 1.8.2 install is a workaround that could be removed once openshift-ansible resolves docker installation issues.

**Comment by thoraxe** [comment]
I dunno what this PR was supposed to fix, but it introduced massive instability. I had to revert it.

openshift-ansible-3.0.47-6 already has resolved the docker installation issues and is a requisite for using this repo (demo-ansible) per the README. 

What was the purpose of the DHCP changes? They caused hostname issues on some instances.

**Comment by detiber** [comment]
@abutcher @cooktheryan: we'll need to revist dhcpopts to find a way that works more reliably.

**Comment by cooktheryan** [comment]
@thoraxe Ill ping you in the morning as I definitely want to check out the parameters you set during run.py and what existed within your aws configuration as it may help with some of the reference architecture work we are doing. The reason for the DHCP changes came due to the nodes not being able find the SDN because it was looking the hosts up by ip-10.1.1.100.ec2.internal but when ec2.internal was added to the DHCP options and attached to the VPC the nodes worked as expected. Definitely any configs we can share will benefit us all massively.  As for the docker lines, it seemed to remedy the issue around docker storage setup (not pretty as @abutcher pointed out but it was a stop gap until we can move forward to docker 1.9+). After the PR, I was able to just run straight through the demo-ansible playbooks with no hands whereas before I would have to either start the installation back over or go to the master and manually finesse docker-storage to start docker.  Sorry for the bug but I think we should be able to knock out a really good long term fix after comparing some notes

**Pull request merged**
