### PR TITLE
3.1 support and updates

### PR DESCRIPTION
**Pull request by detiber**

### CODE REVIEW

**Comment by detiber** [comment]
addresses: https://github.com/2015-Middleware-Keynote/demo-ansible/issues/74 https://github.com/2015-Middleware-Keynote/demo-ansible/issues/73 https://github.com/2015-Middleware-Keynote/demo-ansible/issues/72

**Comment by detiber** [comment]
@ryanj This should address the issues you've been running into.

**Comment by detiber** [comment]
@thoraxe @ryanj latest update to this should fix the issue with re-registration on subsequent runs.

**Comment by ryanj** [comment]
:+1: This is working really well.  I'm in favor of merging this work into 'master'

**Comment by thoraxe** [comment]
I was finally able to make this work myself. The issues I had were not related to the demo-ansible script, but rather to problems with Docker starting which subsequently failed the rest of the provisioning stuff. I think this is probably good to go.

**Pull request merged**
