### PR TITLE
Dockerfile - https://hub.docker.com/r/ryanj/ose-aws-deployer/

### PR DESCRIPTION
**Pull request by ryanj**
See https://hub.docker.com/r/ryanj/ose-aws-deployer/ for example usage info

### CODE REVIEW

**Comment by ryanj** [comment]
Initial feedback:
- We should be able to run this without using the `--privileged` flag. The `--security-opt` flag may be useful
- Try adding a USER line, and support for running with arbitrary UserIDs

**Comment by thoraxe** [comment]
I just submitted a new PR which likely requires you to rebase/rebuild the Dockerfile. Wanna give that a whirl?

Have you tested with both cert-repos and subscriptions?

**Comment by ryanj** [comment]
New release published to DockerHub: https://hub.docker.com/r/ryanj/ose-aws-deployer/
subscriptions work fine, I have not tested cert repos

**Comment by ryanj** [comment]
Let me know if you have any other feedback on this PR. I'm trying to wrap this up by the end of the week (if possible).

**Comment by ryanj** [comment]
Thanks for the quick review from @detiber! Merging...

**Pull request merged**
