### PR TITLE
Use openshift-ansible cloud provider config.

### PR DESCRIPTION
**Pull request by abutcher**
Changes related to https://github.com/openshift/openshift-ansible/pull/1634

### CODE REVIEW

**Comment by detiber** [comment]
nice!

**Comment by abutcher** [comment]
Missed the max-pods config -- adding that shortly.

**Comment by abutcher** [comment]
Added max-pods

```
kubeletArguments:
  cloud-config:
  - /etc/origin/cloudprovider/aws.conf
  cloud-provider:
  - aws
  max-pods:
  - '100'
```

**Comment by detiber** [comment]
Man, we don't expose max_pods as a separate variable yet?

**Comment by abutcher** [comment]
Nope.jpeg

**Comment by thoraxe** [comment]
I don't understand what this PR does...

**Comment by abutcher** [comment]
It does what the removed lines did.

**Comment by alberttwong** [comment]
@abutcher I guess the confusion is that you removed lines but didn't add more instructions/files or added lines

**Comment by abutcher** [comment]
Hey @alberttwong, AWS cloud provider settings were added to openshift-ansible in the PR linked in the description so we can simply set `openshift_cloudprovider_kind: aws` (since demo-ansible utilizes iam profiles there's no need to provide keys)

**Comment by alberttwong** [comment]
I see... so we're removing legacy settings and technical debt.  Got it.

**Comment by thoraxe** [comment]
Testing now.

**Comment by thoraxe** [comment]
This does not work against openshift-ansible-3.0.47-6 -- /etc/origin/aws.conf is not properly created.

**Comment by abutcher** [comment]
Relies on the associated 3.2 openshift-ansible release for packaged ansible scripts. (or the next release which will probably be 3.2)

**Pull request closed without merging**
